# Configuración del SecureOT Insight Agent

# Interfaz de red utilizada para captura de tráfico
interface = "eth0"

# Dirección IP de la central remota
host = "192.168.1.100"

# Puerto utilizado para la transmisión
port = 443

# Habilitar transmisión segura con SSL/TLS
ssl_enabled = true

# Habilitar UDP como método de transmisión alternativo
udp_enabled = false

# Modo de operación: "send" (emisor), "receive" (receptor) o "dual" (ambos)
mode = "dual"

# Activar API REST para gestión remota
api_enabled = true

# Puerto en el que se ejecuta la API REST
api_port = 8080

# Filtros BPF para captura de tráfico
filters = [
    "tcp port 502",  # Captura tráfico Modbus TCP
    "udp port 161",  # Captura tráfico SNMP
]

# Ruta del certificado SSL/TLS (si se usa modo manual)
cert_file = "config/server.crt"
key_file = "config/server.key"

# Configuración de métricas
metrics_enabled = true
metrics_port = 9090

# Nivel de logging: "info", "debug", "error"
log_level = "info"
