[files]
"Cargo.toml" = "Configuración del proyecto y dependencias de Rust."
"src/main.rs" = "Controlador principal del agente, decide si opera en modo emisor, receptor o ambos."
"src/capture.rs" = "Módulo de captura, obtiene tráfico en tiempo real y aplica filtros BPF."
"src/transmit.rs" = "Módulo de transmisión, envía tráfico en UDP, TCP y SSL/TLS."
"src/receive.rs" = "Módulo de recepción, escucha tráfico y lo almacena en formato PCAP."
"src/api.rs" = "API REST activable para control remoto y gestión de filtros en tiempo real."
"src/config.rs" = "Gestión de configuración, permite ajustar parámetros sin recompilar."
"src/metrics.rs" = "Monitoreo de tráfico y rendimiento, integra estadísticas en Prometheus."
"src/utils.rs" = "Funciones auxiliares para manejo de paquetes y memoria."
"Dockerfile" = "Configuración de contenedor Docker para ejecución del agente."
"docker-compose.yml" = "Orquestación en Docker con ejecución flexible."
"README.md" = "Documentación general optimizada para Copilot en VS Code."
